// All possible routes
const role_routes = {
  allRoutes: [
    "/",
    "/abt-us",
    "/abt-yr",
    "/Term_and_Conditions",
    "/trust",
    "/handbook",
    "/v_m",
    "/management",
    "/principal",
    "/dean",
    "/admin",
    "/committee",
    "/clg-org",
    "/departments",
    "/programs",
    "/academic_cal",
    "/dept/001",
    "/dept/002",
    "/dept/003",
    "/dept/004",
    "/dept/005",
    "/dept/006",
    "/dept/007",
    "/dept/008",
    "/dept/009",
    "/dept/010",
    "/dept/011",
    "/dept/012",
    "/dept/013",
    "/dept/014",
    "/dept/015",
    "/dept/016",
    "/facultyprofile/:uid",
    "/ug",
    "/m_e",
    "/mba",
    "/phd",
    "/admission-team",
    "/reg",
    "/Syllabus",
    "/form",
    "/Academic",
    "/coe",
    "/abtplace",
    "/place-team",
    "/place-dep",
    "/Consultancy",
    "/Journal",
    "/policies",
    "/Funded",
    "/Book_Chapter",
    "/Accreditation",
    "/iqac",
    "/iic",
    "/ecell",
    "/incubation",
    "/alumni",
    "/NSS",
    "/NCC",
    "/nccnavy",
    "/nccarmy",
    "/YRC",
    "/sports",
    "/transport",
    "/library",
    "/hosLanding",
    "/other-facilities",
    "/gallery",
    "/gallery_details",
    "/grievances",
    "/webteam",
    "/web_contact",
    "/admin_dash",
    "/admin_approval",
    "/rankholders",
    "/contact_us",
  ],
  research: [
    "/Journal",
    "/Book_Chapter",
    "/Funded",
    "/Consultancy",
    "/policies"
  ],
  exam: [
    "/rankholders",
    "/form",
    "/coe",
    "/reg",
  ],
  about_us: [
    "/abt-us",
    "/trust",
    "/v_m",
    "/management"
  ],
  placement: [
    "/place-dep",
    "/alumni",
    "/place-team"
  ],
  admissions: [
    "/ug",
    "/m_e",
    "/mba",
    "/phd",
    "/admission-team"
  ],
  administration: [
    "/principal",
    "/dean",
    "/admin",
    "/committee",
    "/handbook",
    "/clg-org"
  ],
  academics: [
    "/programs",
    "/departments",
    "/academic_cal"
  ],
  dept_001: ["/dept/001"],
  dept_002: ["/dept/002"],
  dept_003: ["/dept/003"],
  dept_004: ["/dept/004"],
  dept_005: ["/dept/005"],
  dept_006: ["/dept/006"],
  dept_007: ["/dept/007"],
  dept_008: ["/dept/008"],
  dept_009: ["/dept/009"],
  dept_010: ["/dept/010"],
  dept_011: ["/dept/011"],
  dept_012: ["/dept/012"],
  dept_013: ["/dept/013"],
  dept_014: ["/dept/014"],
  dept_015: ["/dept/015"],
  dept_016: ["/dept/016"],

  gallery: ["/gallery"],
  help_desk: ["/grievances"],
  hostel_details: ["/hosLanding"],
  other_facilities: ["/other-facilities"],
  library: ["/library"],
  iic: ["/iic"],
  transport: ["/transport"],
  ecell: ["/ecell"],
  ncc_navy: ["/nccnavy"],
  ncc_army: ["/nccarmy"],
  nss: ["/NSS"],
  yrc: ["/YRC"],
  incubation: ["/incubation"],
  iqac: ["/iqac"],
  accreditations_and_ranking: ["/Accreditation"],
  sports: ["/sports"]
};


const roleRoutes = {
  // Main
  super_admin: role_routes.allRoutes,

  // Top Navigation
  research_admin: role_routes.research,
  exam_admin: role_routes.exam,
  about_us_admin: role_routes.about_us,
  placement_admin: role_routes.placement,
  admissions_admin: role_routes.admissions,
  administration_admin: role_routes.administration,
  academics_admin: role_routes.academics,

  // Department Admins
  dept_001_admin: role_routes.dept_001,
  dept_002_admin: role_routes.dept_002,
  dept_003_admin: role_routes.dept_003,
  dept_004_admin: role_routes.dept_004,
  dept_005_admin: role_routes.dept_005,
  dept_006_admin: role_routes.dept_006,
  dept_007_admin: role_routes.dept_007,
  dept_008_admin: role_routes.dept_008,
  dept_009_admin: role_routes.dept_009,
  dept_010_admin: role_routes.dept_010,
  dept_011_admin: role_routes.dept_011,
  dept_012_admin: role_routes.dept_012,
  dept_013_admin: role_routes.dept_013,
  dept_014_admin: role_routes.dept_014,
  dept_015_admin: role_routes.dept_015,
  dept_016_admin: role_routes.dept_016,

  // Second Navigation
  gallery_admin: role_routes.gallery,
  help_desk_admin: role_routes.help_desk,
  hostel_admin: role_routes.hostel_details,
  other_facilities_admin: role_routes.other_facilities,
  library_admin: role_routes.library,
  iic_admin: role_routes.iic,
  transport_admin: role_routes.transport,
  incubation_admin: [
    ...role_routes.ecell,
    ...role_routes.incubation
  ],
  ncc_navy_admin: role_routes.ncc_navy,
  ncc_army_admin: role_routes.ncc_army,
  nss_admin: role_routes.nss,
  yrc_admin: role_routes.yrc,
  iqac_admin: role_routes.iqac,
  accreditation_admin: role_routes.accreditations_and_ranking,
  sports_admin: role_routes.sports
};

module.exports = { roleRoutes };
