// All possible routes
const allRoutes = [
  "/",
  "/abt-us",
  "/abt-yr",
  "/Term_and_Conditions",
  "/trust",
  "/handbook",
  "/v_m",
  "/management",
  "/principal",
  "/dean",
  "/admin",
  "/committee",
  "/clg-org",
  "/departments",
  "/programs",
  "/acadamic_cal",
  "/dept/:deptID",
  "/facultyprofile/:uid",
  "/ug",
  "/m_e",
  "/mba",
  "/phd",
  "/admission-team",
  "/reg",
  "/Syllabus",
  "/form",
  "/Academic",
  "/coe",
  "/abtplace",
  "/place-team",
  "/place-dep",
  "/Consultancy",
  "/Journal",
  "/policies",
  "/Funded",
  "/Book_Chapter",
  "/Accredation",
  "/iqac",
  "/iic",
  "/ecell",
  "/incubation",
  "/alumni",
  "/NSS",
  "/NCC",
  "/nccnavy",
  "/nccarmy",
  "/YRC",
  "/sports",
  "/transport",
  "/library",
  "/hosLanding",
  "/other-facilities",
  "/gallery",
  "/gallery-details",
  "/grievances",
  "/webteam",
  "/web_contact",
  "/admin_dash",
  "/admin_approval"
];


const roleRoutes = {
  super_admin: allRoutes,
};

module.exports = { roleRoutes };
