// All possible routes
const allRoutes = [
  "/",
  "/abt-us",
  "/abt-yr",
  "/Term_and_Conditions",
  "/trust",
  "/handbook",
  "/vm",
  "/management",
  "/principal",
  "/dean",
  "/admin",
  "/committee",
  "/clg-org",
  "/departments",
  "/programs",
  "/acadamiccal",
  "/dept/001",
  "/dept/002",
  "/dept/003",
  "/dept/004",
  "/dept/005",
  "/dept/006",
  "/dept/007",
  "/dept/008",
  "/dept/009",
  "/dept/010",
  "/dept/011",
  "/dept/012",
  "/dept/013",
  "/dept/014",
  "/dept/015",
  "/dept/016",
  "/facultyprofile/:uid",
  "/ug",
  "/m_e",
  "/mba",
  "/phd",
  "/admission-team",
  "/reg",
  "/Syllabus",
  "/form",
  "/Academic",
  "/coe",
  "/abtplace",
  "/place-team",
  "/place-dep",
  "/Consultancy",
  "/Journal",
  "/policies",
  "/Funded",
  "/Book_Chapter",
  "/Accredation",
  "/iqac",
  "/iic",
  "/ecell",
  "/incubation",
  "/alumni",
  "/NSS",
  "/NCC",
  "/nccnavy",
  "/nccarmy",
  "/YRC",
  "/sports",
  "/transport",
  "/library",
  "/hosLanding",
  "/other-facilities",
  "/gallery",
  "/gallery_details",
  "/grievances",
  "/webteam",
  "/web_contact",
  "/admin_dash",
  "/admin_approval",
  "/rankholders",
  "/contact_us",
];


const roleRoutes = {
  super_admin: allRoutes,
};

module.exports = { roleRoutes };
